set(VALACODEGEN_VALA_SOURCES
  ${CMAKE_SOURCE_DIR}/codegen/valaccodearraymodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaccodeassignmentmodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaccodebasemodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaccodecompiler.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaccodecontrolflowmodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaccodedeclarationspace.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaccodedelegatemodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaccodegenerator.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaccodememberaccessmodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaccodemethodcallmodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaccodemethodmodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaccodemodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaccodestructmodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaclassregisterfunction.vala
  ${CMAKE_SOURCE_DIR}/codegen/valactype.vala
  ${CMAKE_SOURCE_DIR}/codegen/valadbusclientmodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valadbusinterfaceregisterfunction.vala
  ${CMAKE_SOURCE_DIR}/codegen/valadbusmodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valadbusservermodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valaenumregisterfunction.vala
  ${CMAKE_SOURCE_DIR}/codegen/valagerrormodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valagirwriter.vala
  ${CMAKE_SOURCE_DIR}/codegen/valagobjectmodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valagsignalmodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valagtypemodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valagasyncmodule.vala
  ${CMAKE_SOURCE_DIR}/codegen/valainterfaceregisterfunction.vala
  ${CMAKE_SOURCE_DIR}/codegen/valastructregisterfunction.vala
  ${CMAKE_SOURCE_DIR}/codegen/valatyperegisterfunction.vala
  )
