set(VALACCODE_VALA_SOURCES
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeassignment.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodebinaryexpression.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeblock.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodebreakstatement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodecasestatement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodecastexpression.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodecommaexpression.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodecomment.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeconditionalexpression.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeconstant.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodecontinuestatement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodedeclaration.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodedeclarator.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodedostatement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeemptystatement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeenum.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeenumvalue.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeexpression.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeexpressionstatement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeformalparameter.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeforstatement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodefragment.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodefunction.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodefunctioncall.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodefunctiondeclarator.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodegotostatement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeidentifier.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeifstatement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeincludedirective.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeinitializerlist.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeinvalidexpression.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodelabel.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodelinedirective.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodemacroreplacement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodememberaccess.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodemodifiers.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodenewline.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodenode.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeoncesection.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeparenthesizedexpression.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodereturnstatement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodestatement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodestruct.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeswitchstatement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodetypedefinition.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeunaryexpression.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodevariabledeclarator.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodewhilestatement.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodewriter.vala
  ${CMAKE_SOURCE_DIR}/ccode/valaccodeelementaccess.vala
  )
