set(VALACORE_VALA_SOURCES
  ${CMAKE_SOURCE_DIR}/vala/valaaddressofexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valaarraycreationexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valaarraylengthfield.vala
  ${CMAKE_SOURCE_DIR}/vala/valaarraymovemethod.vala
  ${CMAKE_SOURCE_DIR}/vala/valaarrayresizemethod.vala
  ${CMAKE_SOURCE_DIR}/vala/valaarraytype.vala
  ${CMAKE_SOURCE_DIR}/vala/valaassignment.vala
  ${CMAKE_SOURCE_DIR}/vala/valaattribute.vala
  ${CMAKE_SOURCE_DIR}/vala/valabaseaccess.vala
  ${CMAKE_SOURCE_DIR}/vala/valabasicblock.vala
  ${CMAKE_SOURCE_DIR}/vala/valabinaryexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valablock.vala
  ${CMAKE_SOURCE_DIR}/vala/valabooleanliteral.vala
  ${CMAKE_SOURCE_DIR}/vala/valabooleantype.vala
  ${CMAKE_SOURCE_DIR}/vala/valabreakstatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valacastexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valacatchclause.vala
  ${CMAKE_SOURCE_DIR}/vala/valacharacterliteral.vala
  ${CMAKE_SOURCE_DIR}/vala/valaclass.vala
  ${CMAKE_SOURCE_DIR}/vala/valaclasstype.vala
  ${CMAKE_SOURCE_DIR}/vala/valacodecontext.vala
  ${CMAKE_SOURCE_DIR}/vala/valacodegenerator.vala
  ${CMAKE_SOURCE_DIR}/vala/valacodenode.vala
  ${CMAKE_SOURCE_DIR}/vala/valacodevisitor.vala
  ${CMAKE_SOURCE_DIR}/vala/valacodewriter.vala
  ${CMAKE_SOURCE_DIR}/vala/valacomment.vala
  ${CMAKE_SOURCE_DIR}/vala/valaconditionalexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valaconstant.vala
  ${CMAKE_SOURCE_DIR}/vala/valaconstructor.vala
  ${CMAKE_SOURCE_DIR}/vala/valacontinuestatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valacreationmethod.vala
  ${CMAKE_SOURCE_DIR}/vala/valadatatype.vala
  ${CMAKE_SOURCE_DIR}/vala/valadeclarationstatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valadelegate.vala
  ${CMAKE_SOURCE_DIR}/vala/valadelegatetype.vala
  ${CMAKE_SOURCE_DIR}/vala/valadeletestatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valadestructor.vala
  ${CMAKE_SOURCE_DIR}/vala/valadostatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valadynamicmethod.vala
  ${CMAKE_SOURCE_DIR}/vala/valadynamicproperty.vala
  ${CMAKE_SOURCE_DIR}/vala/valadynamicsignal.vala
  ${CMAKE_SOURCE_DIR}/vala/valaelementaccess.vala
  ${CMAKE_SOURCE_DIR}/vala/valaemptystatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valaenum.vala
  ${CMAKE_SOURCE_DIR}/vala/valaenumvalue.vala
  ${CMAKE_SOURCE_DIR}/vala/valaenumvaluetype.vala
  ${CMAKE_SOURCE_DIR}/vala/valaerrorcode.vala
  ${CMAKE_SOURCE_DIR}/vala/valaerrordomain.vala
  ${CMAKE_SOURCE_DIR}/vala/valaerrortype.vala
  ${CMAKE_SOURCE_DIR}/vala/valaexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valaexpressionstatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valafield.vala
  ${CMAKE_SOURCE_DIR}/vala/valafieldprototype.vala
  ${CMAKE_SOURCE_DIR}/vala/valafloatingtype.vala
  ${CMAKE_SOURCE_DIR}/vala/valaflowanalyzer.vala
  ${CMAKE_SOURCE_DIR}/vala/valaforeachstatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valaformalparameter.vala
  ${CMAKE_SOURCE_DIR}/vala/valaforstatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valagirparser.vala
  ${CMAKE_SOURCE_DIR}/vala/valagenerictype.vala
  ${CMAKE_SOURCE_DIR}/vala/valagenieparser.vala
  ${CMAKE_SOURCE_DIR}/vala/valageniescanner.vala
  ${CMAKE_SOURCE_DIR}/vala/valagenietokentype.vala
  ${CMAKE_SOURCE_DIR}/vala/valaifstatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valainitializerlist.vala
  ${CMAKE_SOURCE_DIR}/vala/valaintegerliteral.vala
  ${CMAKE_SOURCE_DIR}/vala/valaintegertype.vala
  ${CMAKE_SOURCE_DIR}/vala/valainterface.vala
  ${CMAKE_SOURCE_DIR}/vala/valainterfacetype.vala
  ${CMAKE_SOURCE_DIR}/vala/valainvalidtype.vala
  ${CMAKE_SOURCE_DIR}/vala/valalambdaexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valalistliteral.vala
  ${CMAKE_SOURCE_DIR}/vala/valaliteral.vala
  ${CMAKE_SOURCE_DIR}/vala/valalocalvariable.vala
  ${CMAKE_SOURCE_DIR}/vala/valalockable.vala
  ${CMAKE_SOURCE_DIR}/vala/valalockstatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valaloop.vala
  ${CMAKE_SOURCE_DIR}/vala/valamapliteral.vala
  ${CMAKE_SOURCE_DIR}/vala/valamarkupreader.vala
  ${CMAKE_SOURCE_DIR}/vala/valamember.vala
  ${CMAKE_SOURCE_DIR}/vala/valamemberaccess.vala
  ${CMAKE_SOURCE_DIR}/vala/valamemberinitializer.vala
  ${CMAKE_SOURCE_DIR}/vala/valamethod.vala
  ${CMAKE_SOURCE_DIR}/vala/valamethodcall.vala
  ${CMAKE_SOURCE_DIR}/vala/valamethodtype.vala
  ${CMAKE_SOURCE_DIR}/vala/valanamedargument.vala
  ${CMAKE_SOURCE_DIR}/vala/valanamespace.vala
  ${CMAKE_SOURCE_DIR}/vala/valanullliteral.vala
  ${CMAKE_SOURCE_DIR}/vala/valanulltype.vala
  ${CMAKE_SOURCE_DIR}/vala/valaobjectcreationexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valaobjecttype.vala
  ${CMAKE_SOURCE_DIR}/vala/valaobjecttypesymbol.vala
  ${CMAKE_SOURCE_DIR}/vala/valaparser.vala
  ${CMAKE_SOURCE_DIR}/vala/valaphifunction.vala
  ${CMAKE_SOURCE_DIR}/vala/valapointerindirection.vala
  ${CMAKE_SOURCE_DIR}/vala/valapointertype.vala
  ${CMAKE_SOURCE_DIR}/vala/valapostfixexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valaprofile.vala
  ${CMAKE_SOURCE_DIR}/vala/valapropertyaccessor.vala
  ${CMAKE_SOURCE_DIR}/vala/valaproperty.vala
  ${CMAKE_SOURCE_DIR}/vala/valarealliteral.vala
  ${CMAKE_SOURCE_DIR}/vala/valareferencetransferexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valareferencetype.vala
  ${CMAKE_SOURCE_DIR}/vala/valaregexliteral.vala
  ${CMAKE_SOURCE_DIR}/vala/valareport.vala
  ${CMAKE_SOURCE_DIR}/vala/valareturnstatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valascanner.vala
  ${CMAKE_SOURCE_DIR}/vala/valascope.vala
  ${CMAKE_SOURCE_DIR}/vala/valasemanticanalyzer.vala
  ${CMAKE_SOURCE_DIR}/vala/valasetliteral.vala
  ${CMAKE_SOURCE_DIR}/vala/valasignal.vala
  ${CMAKE_SOURCE_DIR}/vala/valasignaltype.vala
  ${CMAKE_SOURCE_DIR}/vala/valasizeofexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valasliceexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valasourcefile.vala
  ${CMAKE_SOURCE_DIR}/vala/valasourcelocation.vala
  ${CMAKE_SOURCE_DIR}/vala/valasourcereference.vala
  ${CMAKE_SOURCE_DIR}/vala/valastatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valastatementlist.vala
  ${CMAKE_SOURCE_DIR}/vala/valastringliteral.vala
  ${CMAKE_SOURCE_DIR}/vala/valastruct.vala
  ${CMAKE_SOURCE_DIR}/vala/valastructvaluetype.vala
  ${CMAKE_SOURCE_DIR}/vala/valaswitchlabel.vala
  ${CMAKE_SOURCE_DIR}/vala/valaswitchsection.vala
  ${CMAKE_SOURCE_DIR}/vala/valaswitchstatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valasymbol.vala
  ${CMAKE_SOURCE_DIR}/vala/valasymbolresolver.vala
  ${CMAKE_SOURCE_DIR}/vala/valatemplate.vala
  ${CMAKE_SOURCE_DIR}/vala/valathrowstatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valatokentype.vala
  ${CMAKE_SOURCE_DIR}/vala/valatrystatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valatuple.vala
  ${CMAKE_SOURCE_DIR}/vala/valatypecheck.vala
  ${CMAKE_SOURCE_DIR}/vala/valatypeofexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valatypeparameter.vala
  ${CMAKE_SOURCE_DIR}/vala/valatypesymbol.vala
  ${CMAKE_SOURCE_DIR}/vala/valaunaryexpression.vala
  ${CMAKE_SOURCE_DIR}/vala/valaunlockstatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valaunresolvedsymbol.vala
  ${CMAKE_SOURCE_DIR}/vala/valaunresolvedtype.vala
  ${CMAKE_SOURCE_DIR}/vala/valausingdirective.vala
  ${CMAKE_SOURCE_DIR}/vala/valavaluetype.vala
  ${CMAKE_SOURCE_DIR}/vala/valavoidtype.vala
  ${CMAKE_SOURCE_DIR}/vala/valawhilestatement.vala
  ${CMAKE_SOURCE_DIR}/vala/valayieldstatement.vala
  )
